version: "3.8"
services:
    db:
        image: "mysql:latest"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: mysql2022
        volumes:
          - ./DataBase:/docker-entrypoint-initdb.d
          - ./DataBase/source:/var/lib/mysql
        ports:
          - "3306"
    php:
        build:
            context: ./Main
        ports:
            - 8080:80